#!/bin/bash

# This file was generated by ChatGPT.

# Set the service account name and role
SERVICE_ACCOUNT_NAME="kibana-service-account"
ROLE="kibana_user"

# Create a service account
curl -X POST -u "elastic:<password>" "https://elasticsearch:9200/_security/api_key" -H 'Content-Type: application/json' -d'
{
  "name": "'$SERVICE_ACCOUNT_NAME'",
  "role_descriptors": {
    "'$ROLE'": {
      "cluster": ["all"]
    }
  }
}
'

# Get the service account API key
API_KEY=$(curl -u "elastic:<password>" -X GET "https://elasticsearch:9200/_security/api_key" -H 'Content-Type: application/json' | jq -r '.api_keys[] | select(.name == "'$SERVICE_ACCOUNT_NAME'") | .id')

# Save the API key to a file
echo "$API_KEY" > /usr/share/kibana/config/service_account_token

