version: '3.7'

services:
  elasticsearch:
    container_name: ddev-${DDEV_SITENAME}-elasticsearch
    hostname: ${DDEV_SITENAME}-elasticsearch
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    image: elasticsearch:8.5.3
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200:9200
#      - HTTPS_EXPOSE=9300:9300
      - xpack.security.transport.ssl.enabled=false
    expose:
      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - "./certs:/app/certs"
#      - elasticsearch-certs:/usr/share/elasticsearch/config/certs
#      - "./elasticsearch:/usr/share/elasticsearch/config"
    #command: ["yes | ./bin/elasticsearch-reset-password -a -f -s -u elastic > pass.txt"]
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail -s http://localhost:9200" ]
      start_period: 10s
#      interval: 30s
#      timeout: 60s


  kibana:
    container_name: ddev-${DDEV_PROJECT}-kibana
    hostname: ${DDEV_PROJECT}-kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    restart: "no"
    environment:
      - SERVER_NAME=kibana.example.com
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SSL_CA=./certs/ca/ca.crt
    ports:
      - "5601:5601"
    expose:
      - '5601'
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - kibana-config:/usr/share/kibana/config
      - kibana-certs:/usr/share/kibana/config/certs
      - "./scripts:/app/scripts"
    links:
      - elasticsearch
#    command: ["/app/scripts/generate_service_account_token.sh"]
    depends_on:
      - elasticsearch


volumes:
  elasticsearch-data:
    driver: local
  elasticsearch-certs:
    driver: local
  kibana-config:
    driver: local
  kibana-certs:
    driver: local
